### ISSUE TITLE
[fix] 아카이브 저장/삭제 버그 수정

### ISSUE THREAD

**Issue by duckbill413** [DDD-Community/DDD-9-Android3-Server#18]
##  📎 Feature Issue

상품 아카이브 버그 수정

## 📝 To-Do
- [x] 아카이브 Transaction 처리 확인
- [x] 아카이브 저장 버그 수정
- [x] 아카이브 삭제 버그 수정

**Comment by duckbill413** [comment]
아카이브 생성, 삭제 테스트 결과 이상 없이 생성/삭제가 이루어짐
> Client단에서 작업중 예상 되는 문제 이유
> - Callback 시간이 짧아서 크롤링이 완료되기 전에 Callback 시간이 종료될 수 있음
> - PostController의 게시물 등록 부하테스트(연속 100회) 결과  30분 정도 소요.

**Comment by duckbill413** [comment]
### `@Builder(access = AccessLevel.PRIVATE)` 활용시 문제
Builder pattern에서 AccessLevel.PRIVATE를 이용하면 생성자를 이용해서 내부적으로 Builder을 사용해야 합니다.
이때 변수 초기화를 `private List<String> itemUrls = new ArrayList<>();`와 같이 dto를 생성하면서 초기화를 하려고 한다면 제대로 적용되지 않는다.
생성자를 이용하여 초기화와 예외처리를 하려면 Builder에
`itemUrls(Objects.nonNull(itemUrls) ? itemUrls : List.of())`
위와 같이 처리해 주어야 한다.

**Comment by duckbill413** [comment]
### JPA Cascade와 Orphanremoval
- Cascade : `CascadeType.REMOVE`
`CascadeType.REMOVE`는 부모 엔티티가 삭제되면 자식 엔티티도 삭제된다. 이때 삭제라는 것은 부모 <-> 자식간의 연관관계 삭제를 의미한다.
- Orphanremoval : `Orphanremoval=true`
`CascadeType.REMOVE`를 이용할 경우 연관관계는 삭제되지만 실제 Entity는 삭제되지 않고 남아있게 된다. 이때, `Orphanremoval=true` 옵션을 사용한다면 연관관계가 삭제되면서 자식 Entity도 고아로 취급되어 그대로 삭제되게 된다.
```java
@OneToMany(
    mappedBy = "team",
    fetch = FetchType.LAZY,
    cascade = CascadeType.PERSIST,
    orphanRemoval = true
)
private List<Member> members = new ArrayList<>();
```

**Comment by minaamim** [comment]
감사합니다!!

**Comment by duckbill413** [comment]
- 아카이브 생성/삭제 확인
- Builder 수정
- Valid 수정 및 유효성 검사 필요한 필드에 추가
